// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"
	calendar "hungry-baby/businesses/calendar"

	mock "github.com/stretchr/testify/mock"
)

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, id
func (_m *Usecase) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: ctx, search, startAt, endAt, pageToken, limit
func (_m *Usecase) FindAll(ctx context.Context, search string, startAt string, endAt string, pageToken string, limit int) ([]calendar.Domain, error) {
	ret := _m.Called(ctx, search, startAt, endAt, pageToken, limit)

	var r0 []calendar.Domain
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, int) []calendar.Domain); ok {
		r0 = rf(ctx, search, startAt, endAt, pageToken, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]calendar.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, int) error); ok {
		r1 = rf(ctx, search, startAt, endAt, pageToken, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *Usecase) FindByID(ctx context.Context, id string) (calendar.Domain, error) {
	ret := _m.Called(ctx, id)

	var r0 calendar.Domain
	if rf, ok := ret.Get(0).(func(context.Context, string) calendar.Domain); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(calendar.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: ctx, calendarDomain
func (_m *Usecase) Store(ctx context.Context, calendarDomain *calendar.Domain) (calendar.Domain, error) {
	ret := _m.Called(ctx, calendarDomain)

	var r0 calendar.Domain
	if rf, ok := ret.Get(0).(func(context.Context, *calendar.Domain) calendar.Domain); ok {
		r0 = rf(ctx, calendarDomain)
	} else {
		r0 = ret.Get(0).(calendar.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *calendar.Domain) error); ok {
		r1 = rf(ctx, calendarDomain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
