// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import (
	context "context"
	country "hungry-baby/businesses/country"

	mock "github.com/stretchr/testify/mock"
)

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

// GetAll provides a mock function with given fields: ctx
func (_m *Usecase) GetAll(ctx context.Context) ([]country.Domain, error) {
	ret := _m.Called(ctx)

	var r0 []country.Domain
	if rf, ok := ret.Get(0).(func(context.Context) []country.Domain); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]country.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByActive provides a mock function with given fields: ctx, active
func (_m *Usecase) GetByActive(ctx context.Context, active bool) ([]country.Domain, error) {
	ret := _m.Called(ctx, active)

	var r0 []country.Domain
	if rf, ok := ret.Get(0).(func(context.Context, bool) []country.Domain); ok {
		r0 = rf(ctx, active)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]country.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, bool) error); ok {
		r1 = rf(ctx, active)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *Usecase) GetByID(ctx context.Context, id int) (country.Domain, error) {
	ret := _m.Called(ctx, id)

	var r0 country.Domain
	if rf, ok := ret.Get(0).(func(context.Context, int) country.Domain); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(country.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
