// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"
	userChildMeal "hungry-baby/businesses/userChildMeal"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, userChildMealDomain
func (_m *Repository) Delete(ctx context.Context, userChildMealDomain *userChildMeal.Domain) (userChildMeal.Domain, error) {
	ret := _m.Called(ctx, userChildMealDomain)

	var r0 userChildMeal.Domain
	if rf, ok := ret.Get(0).(func(context.Context, *userChildMeal.Domain) userChildMeal.Domain); ok {
		r0 = rf(ctx, userChildMealDomain)
	} else {
		r0 = ret.Get(0).(userChildMeal.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *userChildMeal.Domain) error); ok {
		r1 = rf(ctx, userChildMealDomain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Find provides a mock function with given fields: ctx, search, userChildID, page, perpage
func (_m *Repository) Find(ctx context.Context, search string, userChildID int, page int, perpage int) ([]userChildMeal.Domain, int, error) {
	ret := _m.Called(ctx, search, userChildID, page, perpage)

	var r0 []userChildMeal.Domain
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int, int) []userChildMeal.Domain); ok {
		r0 = rf(ctx, search, userChildID, page, perpage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]userChildMeal.Domain)
		}
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(context.Context, string, int, int, int) int); ok {
		r1 = rf(ctx, search, userChildID, page, perpage)
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, string, int, int, int) error); ok {
		r2 = rf(ctx, search, userChildID, page, perpage)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindAll provides a mock function with given fields: ctx, search, userChildID
func (_m *Repository) FindAll(ctx context.Context, search string, userChildID int) ([]userChildMeal.Domain, error) {
	ret := _m.Called(ctx, search, userChildID)

	var r0 []userChildMeal.Domain
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []userChildMeal.Domain); ok {
		r0 = rf(ctx, search, userChildID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]userChildMeal.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, search, userChildID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByChildMeal provides a mock function with given fields: ctx, userChildID, mealPlanID
func (_m *Repository) FindByChildMeal(ctx context.Context, userChildID int, mealPlanID int) (userChildMeal.Domain, error) {
	ret := _m.Called(ctx, userChildID, mealPlanID)

	var r0 userChildMeal.Domain
	if rf, ok := ret.Get(0).(func(context.Context, int, int) userChildMeal.Domain); ok {
		r0 = rf(ctx, userChildID, mealPlanID)
	} else {
		r0 = ret.Get(0).(userChildMeal.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, userChildID, mealPlanID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *Repository) FindByID(ctx context.Context, id int) (userChildMeal.Domain, error) {
	ret := _m.Called(ctx, id)

	var r0 userChildMeal.Domain
	if rf, ok := ret.Get(0).(func(context.Context, int) userChildMeal.Domain); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(userChildMeal.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindNextPending provides a mock function with given fields: ctx, userChildID, mealPlanID
func (_m *Repository) FindNextPending(ctx context.Context, userChildID int, mealPlanID int) (userChildMeal.Domain, error) {
	ret := _m.Called(ctx, userChildID, mealPlanID)

	var r0 userChildMeal.Domain
	if rf, ok := ret.Get(0).(func(context.Context, int, int) userChildMeal.Domain); ok {
		r0 = rf(ctx, userChildID, mealPlanID)
	} else {
		r0 = ret.Get(0).(userChildMeal.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, userChildID, mealPlanID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: ctx, userChildMealDomain
func (_m *Repository) Store(ctx context.Context, userChildMealDomain *userChildMeal.Domain) (userChildMeal.Domain, error) {
	ret := _m.Called(ctx, userChildMealDomain)

	var r0 userChildMeal.Domain
	if rf, ok := ret.Get(0).(func(context.Context, *userChildMeal.Domain) userChildMeal.Domain); ok {
		r0 = rf(ctx, userChildMealDomain)
	} else {
		r0 = ret.Get(0).(userChildMeal.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *userChildMeal.Domain) error); ok {
		r1 = rf(ctx, userChildMealDomain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, userChildMealDomain
func (_m *Repository) Update(ctx context.Context, userChildMealDomain *userChildMeal.Domain) (userChildMeal.Domain, error) {
	ret := _m.Called(ctx, userChildMealDomain)

	var r0 userChildMeal.Domain
	if rf, ok := ret.Get(0).(func(context.Context, *userChildMeal.Domain) userChildMeal.Domain); ok {
		r0 = rf(ctx, userChildMealDomain)
	} else {
		r0 = ret.Get(0).(userChildMeal.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *userChildMeal.Domain) error); ok {
		r1 = rf(ctx, userChildMealDomain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
